'use client'   ///IF WE ARE USING ANY HOOK IN NEXT.JS THEN WE NEED TO USE THIS 'USE CLIENT' AT THE TOP OF THE FILE.
//  THIS IS BECAUSE NEXT.JS BY DEFAULT RENDER THE COMPONENTS ON THE SERVER SIDE AND IF WE ARE USING ANY HOOK THEN IT WILL THROW AN ERROR BECAUSE HOOKS CAN ONLY BE USED IN CLIENT SIDE RENDERING.
//  SO TO AVOID THIS ERROR WE NEED TO USE THIS 'USE CLIENT' AT THE TOP OF THE FILE.
import React from 'react'
import { useParams } from 'next/navigation'

const page = () => {
    const params = useParams()
    console.log(params)

  return (
    <div>
      <h1>{params.id} Course</h1>   
    </div>
  )
}

export default page

///THIS IS CALLED DYNAMIC ROUTING IN NEXT.JS. 
// DYNAMIC ROUTING MEANS THAT WE CAN CREATE A ROUTE WHICH CAN ACCEPT ANY VALUE AS A PARAMETER AND THEN WE CAN USE THAT PARAMETER TO FETCH THE DATA OF THE PARTICULAR COURSE WHICH WE WANT TO DISPLAY.
///FOR DYNAMIC ROUTING WE NEED TO CREATE A FOLDER WITH NAME [id] INSIDE THE COURSES FOLDER AND THEN CREATE A PAGE.JS FILE INSIDE IT. 
// THIS ID CAN BE ANY NAME BUT IT SHOULD BE IN SQUARE BRACKETS. THIS ID WILL BE USED TO FETCH THE DATA OF THE PARTICULAR COURSE WHICH WE WANT TO DISPLAY. 
// FOR EXAMPLE IF WE WANT TO DISPLAY THE DATA OF THE COURSE WITH ID 1 THEN WE WILL USE THE URL /courses/1 AND IF WE WANT TO DISPLAY THE DATA OF THE COURSE WITH ID 2 THEN WE WILL USE THE URL /courses/2 AND SO ON. 
// THIS ID CAN BE USED TO FETCH THE DATA FROM THE DATABASE OR FROM ANY API.
