import React from 'react'

const page = () => {
  return (
    <div>
      <h1 className='text-3xl underline'>This is Home section</h1>
    </div>
  )
}

export default page


///ROUTING IN NEXT.JS

// 1. File based routing
// 2. Dynamic routing
// 3. Nested routing
// 4. API routes

// - IF YOU WANT TO PERFORM ROUTING IN NEXT.JS, JUST CREATE A FOLDER INSIDE APP FOLDER
// - THE NAME OF THE FOLDER SHOULD BE THE NAME OF THE ROUTE
// - INSIDE THAT FOLDER, CREATE A FILE NAMED PAGE.JS
// - THIS PAGE.JS FILE WILL BE THE COMPONENT THAT WILL BE RENDERED WHEN THE USER VISITS THAT ROUTE

// - FOR EXAMPLE, IF YOU WANT TO CREATE A ROUTE NAMED ABOUT, THEN CREATE A FOLDER NAMED ABOUT INSIDE APP FOLDER AND INSIDE THAT FOLDER CREATE A FILE NAMED PAGE.JS
// - NOW, WHEN THE USER VISITS /ABOUT, THE COMPONENT INSIDE ABOUT/PAGE.JS WILL BE RENDERED